name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - name: Lint
        if: matrix.os == 'ubuntu-22.04'
        run: zig fmt --check .
      - name: Build and run examples
        working-directory: example
        run: zig build run
